# Generated by Django 2.1.7 on 2019-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadWarrior_app', '0003_auto_20190221_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='DESCRIPTION', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.TextField(default='IMAGE'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='TITLE', max_length=100),
        ),
    ]
