# Generated by Django 2.1.7 on 2019-02-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadWarrior_app', '0004_auto_20190222_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commentText', models.CharField(max_length=500)),
                ('commentVoteCount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.TextField(default='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roadWarrior_app.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rvId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roadWarrior_app.RV'),
        ),
    ]
