# Generated by Django 2.1.7 on 2019-02-23 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roadWarrior_app', '0005_auto_20190222_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='commentDate',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentVoteCount',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
