# Generated by Django 2.1.7 on 2019-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadWarrior_app', '0006_auto_20190223_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rv',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.TextField(default='Image', null=True),
        ),
        migrations.AlterField(
            model_name='rv',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
