# Generated by Django 2.1.7 on 2019-02-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadWarrior_app', '0008_auto_20190226_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rvId',
            field=models.ForeignKey(db_column='vehicleName', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roadWarrior_app.RV'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rv',
            field=models.ForeignKey(db_column='vehicleName', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='roadWarrior_app.RV'),
        ),
    ]
