# Generated by Django 2.1.7 on 2019-02-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadWarrior_app', '0009_auto_20190226_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rvId',
            new_name='vehicleName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rv',
            new_name='vehicleName',
        ),
    ]
